# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-62a3e4ad-42d3-44bc-b917-c5b22a7f7483";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-62a3e4ad-42d3-44bc-b917-c5b22a7f7483".device = "/dev/disk/by-uuid/62a3e4ad-42d3-44bc-b917-c5b22a7f7483";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/19A6-B813";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-b1537fd3-aff5-400e-b1ce-7325593d38d5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth.enable = true;

  hardware.ledger.enable = true;
}
